import customtkinter as ctk
import Style as st
import WelcomeScrean as ws
import LogIn as li
import SignUp as su
import MainPage as mp
import DetailsPage as dp
import AIHelperPage as ai
import Support as sp
import Account as ac
